package com.ascstb.mangaapp5.model

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

@Parcelize
data class SearchParameters(
    var nameMethod: String = "cw",
    var name: String = "",
    var authorMethod: String = "cw",
    var author: String = "",
    var artistMethod: String = "cw",
    var artist: String = "",
    var type: String = "",
    var demographic: String = "",
    var genres4Koma: Int = 0,
    var genresAction: Int = 0,
    var genresAdventure: Int = 0,
    var genresComedy: Int = 0,
    var genresCooking: Int = 0,
    var genresDoujinshi: Int = 0,
    var genresDrama: Int = 0,
    var genresEcchi: Int = 0,
    var genresFantasy: Int = 0,
    var genresGenderBender: Int = 0,
    var genresHarem: Int = 0,
    var genresHistorical: Int = 0,
    var genresHorror: Int = 0,
    var genresJosei: Int = 0,
    var genresLolicon: Int = 0,
    var genresMartialArts: Int = 0,
    var genresMature: Int = 0,
    var genresMecha: Int = 0,
    var genresMusic: Int = 0,
    var genresMystery: Int = 0,
    var genresOneShot: Int = 0,
    var genresPsychological: Int = 0,
    var genresReverseHarem: Int = 0,
    var genresRomance: Int = 0,
    var genresSchoolLife: Int = 0,
    var genresSciFi: Int = 0,
    var genresSciMFi: Int = 0,
    var genresSeinen: Int = 0,
    var genresShotacon: Int = 0,
    var genresShoujo: Int = 0,
    var genresShoujoAi: Int = 0,
    var genresShounen: Int = 0,
    var genresShounenAi: Int = 0,
    var genresSliceOfLife: Int = 0,
    var genresSmut: Int = 0,
    var genresSports: Int = 0,
    var genresSupernatural: Int = 0,
    var genresSuspense: Int = 0,
    var genresTragedy: Int = 0,
    var genresVampire: Int = 0,
    var genresWebtoons: Int = 0,
    var genresYoukai: Int = 0,
    var releasedMethod: String = "eq",
    var released: String = "",
    var ratingMethod: String = "eq",
    var rating: String = "",
    var advopts: String = ""
) : Parcelable